# easterhegg20_fahrplan
# This is the pubspec file specifying all dependencies
# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2019 - 2021 Benjamin Schilling

name: easterhegg20_fahrplan
description: Easterhegg20 Fahrplan written in flutter

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.2+31

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # I18N
    sdk: flutter

  alarm: ^0.2.9
  connectivity_plus: ^3.0.3
  device_calendar: ^4.3.1
  flutter_linkify: ^5.0.2
  flutter_svg: ^2.0.4
  http: ^0.13.5
  intl: ^0.17.0
  package_info: ^2.0.2
  page_view_indicators: ^2.0.0
  path_provider: ^2.0.14
  permission_handler: ^10.2.0
  provider: ^6.0.5
  share: ^2.0.4
  timezone: ^0.9.1
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_oss_licenses: ^2.0.1
  flutter_test:
    sdk: flutter
  intl_utils: ^2.8.2

# see https://plugins.jetbrains.com/plugin/13666-flutter-intl
# arb file format: https://localizely.com/flutter-arb/
flutter_intl:
  enabled: true
  class_name: S
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
